"""
Configuration constants for Valuebell Transcriber
"""

# Application metadata
APP_NAME = "Valuebell Transcriber"
APP_DESCRIPTION = "*Upload your audio or video files to get accurate transcripts with automatic speaker detection. Perfect for podcasts, interviews, and meetings.*"

# Audio processing settings
DEFAULT_SAMPLE_RATE = 16000  # Optimal for speech-to-text
DEFAULT_CHANNELS = 1  # Mono
HIGH_QUALITY_BITRATE = "320k"  # For MP3 conversion
STANDARD_MP3_SAMPLE_RATE = 44100

# File size limits
MAX_WAV_SIZE_GB = 1  # Convert to MP3 if larger than 1GB
MAX_WAV_SIZE_BYTES = MAX_WAV_SIZE_GB * 1024 * 1024 * 1024

# SRT subtitle settings
MAX_CUE_DURATION_SECONDS = 7
MAX_CUE_CHARACTERS = 120

# Quality analysis thresholds
OUTLIER_Z_SCORE_THRESHOLD = 3
ABNORMAL_FINAL_TOKEN_DURATION = 10  # seconds
INCOMPLETE_TRANSCRIPT_THRESHOLD = 5  # seconds of unaccounted audio

# Supported file types
SUPPORTED_AUDIO_EXTENSIONS = [".mp3", ".wav", ".m4a"]
SUPPORTED_VIDEO_EXTENSIONS = [".mp4", ".avi", ".mov"]
SUPPORTED_JSON_EXTENSIONS = [".json"]

ALL_SUPPORTED_EXTENSIONS = (
    SUPPORTED_AUDIO_EXTENSIONS +
    SUPPORTED_VIDEO_EXTENSIONS +
    SUPPORTED_JSON_EXTENSIONS
)

# Language options
SUPPORTED_LANGUAGES = [
    ("Hebrew", "heb"),
    ("English", "en"),
    ("Spanish", "es"),
    ("French", "fr"),
    ("German", "de"),
    ("Italian", "it"),
    ("Portuguese", "pt"),
    ("Russian", "ru"),
    ("Chinese", "zh"),
    ("Japanese", "ja"),
    ("Korean", "ko")
]

# Hugging Face Spaces configuration
HF_SERVER_NAME = "0.0.0.0"
HF_SERVER_PORT = 7860

# Disclaimer text
TRANSCRIPT_DISCLAIMER = """⚠️  TRANSCRIPT DISCLAIMER ⚠️
This transcript was generated using AI technology and may contain errors,
inaccuracies, or misinterpretations. Please review and verify the content
before using it for any official, legal, or critical purposes.
Generated by: Valuebell Transcriber
═══════════════════════════════════════════════════════════════════════════

"""